<a href="https://colab.research.google.com/github/beyzanurbayir/PythonProjects/blob/master/NumpyAlisi%C4%B1rmalari.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Alıştırma:

İki vektörün iç çarpımını hesaplayan bir fonksiyon oluşturmak.

In [4]:
import numpy as np

In [5]:
def InnerProduct(V1,V2):
  return V1*V2

In [6]:
V1 = np.array([1,2,3])
V2 = np.array([4,5,6])

In [7]:
print(InnerProduct(V1,V2))

[ 4 10 18]


2. Alıştırma:

Belirli bir aralıktaki sayıların ortalamasını hesaplayan kod

In [21]:
import numpy as np

In [29]:
arr1= np.arange(25)

In [30]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
result=0
for i in arr1:
  result += i

print(result)

300


3. Alıştırma:

İki matrisin çarpımını hesaplayan bir fonksiyon oluşturmak

In [37]:
import numpy as np

In [38]:
M1= np.random.randint(1,100,(5,5))
M2= np.random.randint(1,100,(5,5))

In [39]:
M1

array([[27, 44, 23, 86, 55],
       [83, 84, 70, 10, 26],
       [76, 14,  2, 18, 62],
       [46, 12, 34, 35, 53],
       [ 5, 80, 20, 30, 23]])

In [40]:
M2

array([[35, 58, 45, 34, 32],
       [97, 89, 70, 66, 98],
       [51, 58, 20, 76,  5],
       [53, 87, 15, 55, 99],
       [53, 85, 79, 25, 52]])

In [41]:
def MatrixMultiplication(M1,M2):
  return M1*M2

In [42]:
MatrixMultiplication(M1,M2)

array([[ 945, 2552, 1035, 2924, 1760],
       [8051, 7476, 4900,  660, 2548],
       [3876,  812,   40, 1368,  310],
       [2438, 1044,  510, 1925, 5247],
       [ 265, 6800, 1580,  750, 1196]])

4. Alıştırma:

Bir matrisin determinantını hesaplayan bir fonksiyon oluşturmak.

In [47]:
import numpy as np

In [48]:
matris=np.random.randint(1,100,(5,5))

In [49]:
matris

array([[33, 16, 64, 69,  7],
       [12,  3, 68, 97, 24],
       [87, 84, 84, 46, 22],
       [48,  8, 46, 76, 27],
       [25, 35,  3, 46,  2]])

In [50]:
np.linalg.det(matris)   # Matrisin determinantını hesaplar

236699242.99999923

In [51]:
round(np.linalg.det(matris))   # Hesaplanan determinantı en yakın sayıya yuvarlar

236699243

5. Alıştırma:

Verilen bir matrisin tersini hesaplayan kod oluşturmak.

In [52]:
import numpy as np

In [54]:
M = np.random.randint(0,100,(5,5))

In [55]:
M

array([[25, 33, 61, 45, 16],
       [98, 24, 68,  7, 56],
       [27, 25, 50,  0, 69],
       [14, 27, 88, 24, 39],
       [ 7, 29, 25, 75, 19]])

In [56]:
np.linalg.inv(M)    # Matrisin tersini almayı sağlayan fonksiyon

array([[ 0.00142933,  0.01267538, -0.006698  , -0.00703999,  0.00021216],
       [ 0.1019391 , -0.02640084,  0.04499568, -0.06506659, -0.03787807],
       [-0.01048848,  0.00297702, -0.0132737 ,  0.0243833 , -0.00178742],
       [-0.0284807 ,  0.00741271, -0.01499077,  0.01549437,  0.0247717 ],
       [-0.02989341,  0.00244833,  0.01042955,  0.00866057,  0.01493615]])

6. Alıştırma:



In [66]:
import numpy as np

In [67]:
Array1 = np.random.randint(0,100,(5,5))
Array2 = np.random.randint(0,100,(5,5))

In [68]:
print("Üzerinde işlem yapılacak olan matrisler sırasıyla şunlardır: ")
print("1. Matris:")
print(Array1)
print("\n2. Matris:")
print(Array2)
print("\n\n")
secim =int(input("Lütfen matrisler üzerinde yapmak istediğiniz işlemi seçiniz:\n1. Toplama\n2. Çıkarma\n3. Çarpma\n\n"))

if secim == 1:
  print("Toplama işlemi yapılıyor...\nSonuc:")
  print(Array1 + Array2)
elif secim == 2:
  print("Çıkarma işlemi yapılıyor...\nSonuc:")
  print(Array1 - Array2)
elif secim == 3:
  print("Çarpma işlemi yapılıyor...\nSonuc:")
else:
  print("Geçersiz seçim yaptınız.")

Üzerinde işlem yapılacak olan matrisler sırasıyla şunlardır: 
1. Matris:
[[85 19 87 78 32]
 [92 25 51 94 72]
 [ 3  1 41 87 53]
 [16  6 97 45 66]
 [14 78  6  4 68]]

2. Matris:
[[23 32 72 50 63]
 [95 78 38 27 58]
 [22 27 31 29 20]
 [90 78 61 87 41]
 [ 4 83 11 44 18]]



Lütfen matrisler üzerinde yapmak istediğiniz işlemi seçiniz:
1. Toplama
2. Çıkarma
3. Çarpma

1
Toplama işlemi yapılıyor...
Sonuc:
[[108  51 159 128  95]
 [187 103  89 121 130]
 [ 25  28  72 116  73]
 [106  84 158 132 107]
 [ 18 161  17  48  86]]
